### ISSUE TITLE
Project [$520]

### ISSUE THREAD

**Issue by PatrickFaure** [PatrickFaure/bouya#1]
Welcome to the crowdfunding page for Rapid-Bouya

Contributions will go into the team’s account and can be used for bounties immediately, or withdrawn by the team as needed. If you enjoy Rapid-Bouya's work and want to show your support every dollar helps!

This is the developer site for Rapid-Bouya. You have access to the source code of Rapid-Bouya, the issue tracker and the mailing lists. If you are a user of Rapid-Bouya you might want to take a look at https://www.Rapid-Bouya.org where we are working on the Documentation and Online Help of Rapid-Bouya

Rapid-Bouya is a cross-platform GUI front-end for the Subversion revision system written in C++ using the wxWidgets framework. This project also includes a Subversion client C++ API. Mission

We want to build a best of breed visual client that utilizes the best features of clients from other revision control architectures. While being easy enough for users new to Subversion to work with it must also be powerful enough to make experienced users even more productive. Features

```
Simple - provides an easy to use interface for Subversion features
Efficient - simple for beginners but flexible enough to increase productivity for experienced Subversion users
Portable - runs on any platform on which Subversion and wxWidgets can run: Linux, Windows, Mac OS/X, Solaris, etc.
Fast - entirely written in C++
Multilingual - it has been translated to many languages already: German, French, Italian, Portuguese, Russian, Ukrainian, Simplified Chinese, Japanese
Full support for Unicode
```
Dependencies

RapidSVN depends on a couple of frameworks. So if you want to compile Rapid-Bouya you have to download, configure and compile these frameworks first (unless you have access to a precompiled binary package with development files like headers and libraries included).

```
Subversion 1.3 or higher download (we work with Subversion 1.7.1)
wxWidgets 2.6.2 or higher download (we work with wxWidgets 2.8)
Roadmap Version Status Scheduled Released Remarks 0.9.8 Released Q2 2014 Mar 19 2015 CHANGES. 0.10 Released Q2 2014 July 17 2015 CHANGES. 0.12 Released Q2 2015 Oct 14 2015 CHANGES. 0.14 Released Q4 2015 Jan 19 2016 CHANGES. 0.16 In-Work Q4 2016
```

Issues for this release.

Follow the link for a list of not scheduled issues. Note: If you have suggestions for future features or would like to see a feature in one of the next scheduled releases, write an email to the developper mailing list or submit a feature request to the issue tracker. To enter an issue, you must first be a member project.

Archived roadmap items.... Building from source

```
Latest source
The source is stored in a GIT repository so in order to get the source code you may either download the GIT command-line client or a GUI tool like GitExtensions.

The URL for the latest code is: https://salt.bountysource.com/teams/rapid-bouya
Download a source tarball.
```
Contributing

Rapid-Bouya is always in need of donors. If you are interested in helping with some of the other developers then join the development of this project, (salt)bountysource is the best place. This project goes by a few coding conventions so please read the Hacker's Guide To Rapid-Bouya.

If you want to know what needs to be done for the first release or submit a bug then use the Issue Tracker.

We hope you enjoyed the project!

Thanks,

Team Rapid-Bouya

**Comment by dmiller423** [comment]
This is confusing, and your salt url gets a 404...

**Comment by PatrickFaure** [comment]
it's update
